export default Vehicules = [
	{
        "key": "vqvk155712Ghdzjjx",
        "imageUrl": "https://i.le360.ma/fr/sites/default/files/styles/asset_image_in_body/public/assets/images/2019/01/new-renault-clio-2019-1079285.jpg",
        "marque": "Renault Clio",
        "numéro_immatriculation": "16-B-11736",
        "idvehicule": 223,
        "idpropriétaire":1,
        "dateintervention": "19/01/2020",
        "dernierevidange": "19/01/2020",
        "kilometrage": "110000",
        "detail1": "detail1",
        "detailderniereintervention": "detailderniereintervention",
        "imagepromoUrl": "https://i2.wp.com/www.carideal.com/blog/wp-content/uploads/2017/03/promo-vidange.jpg?fit=500%2C150",
        "duree": "du 14 Decembre 2019 à 23 Janvier 2020",
        "prix": "prix en DHs",
        "description":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
        "dateachatpromo":"19/01/2020",
        "dureepromopub":"du 1er Aout 2020 à 20 Septembre 2020",
        "prixpromopub":"prix",
        "descriptionpromopub":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
    },
    {
        "key": "vqvk155712Ghdzjjx",
        "imageUrl": "https://www.mercedes-benz.fr/passengercars/_jcr_content/image.MQ6.2.2x.20190123105639.png",
        "marque": "Mercedes classe A",
        "numéro_immatriculation": "16-B-11736",
        "idvehicule": 230,
        "idpropriétaire":1,
        "dateintervention": "19/01/2020",
        "dernierevidange": "19/01/2020",
        "kilometrage": "110000",
        "detail1": "detail1",
        "detailderniereintervention": "detailderniereintervention",
        "imagepromoUrl": "https://i2.wp.com/www.carideal.com/blog/wp-content/uploads/2017/03/promo-vidange.jpg?fit=500%2C150",
        "duree": "du 14 Aout 2020 à 20 Septembre 2020",
        "prix": "prix en DHs",
        "description":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
        "dateachatpromo":"19/01/2020",
        "dureepromopub": "du 14 Juillet 2020 à 14 Aout 2020",
        "prixpromopub":"prix",
        "descriptionpromopub":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
    },
    {
        "key": "vjhdzgu428BUH8èfv",
        "imageUrl": "https://www.mercedes-benz.fr/passengercars/_jcr_content/image.MQ6.2.2x.20190123105639.png",
        "marque": "Mercedes classe A",
        "numéro_immatriculation": "44-A-12766",
        "idvehicule": 224,
        "idpropriétaire":1,
        "dateintervention": "21/04/2019",
        "dernierevidange": "19/01/2020",
        "kilometrage": "110000",
        "detail1": "detail1",
        "detailderniereintervention": "detailderniereintervention",
        "imagepromoUrl": "https://i2.wp.com/www.carideal.com/blog/wp-content/uploads/2017/03/promo-vidange.jpg?fit=500%2C150",
        "duree": "du 14 Juillet 2020 à 14 Aout 2020",
        "prix": "prix en DHs",
        "description":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
        "dateachatpromo":"19/01/2020",
        "dureepromopub": "du 14 Juillet 2020 à 14 Aout 2020",
        "prixpromopub":"prix",
        "descriptionpromopub":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
    },
    {
        "key": "GYU155ffzggdàj99",
        "imageUrl": "https://www.citroen.ma/wp-content/uploads/2016/11/NouvelleC3-blanc-banquise-AR.jpg",
        "marque": "Citroen C3",
        "numéro_immatriculation": "17-A-73459",
        "idvehicule": 222,
        "dateintervention": "12/03/2019",
        "idpropriétaire": 2,
        "dernierevidange": "19/01/2020",
        "kilometrage": "110000",
        "detail1": "detail1",
        "detailderniereintervention": "detailderniereintervention",
       "imagepromoUrl": "https://i2.wp.com/www.carideal.com/blog/wp-content/uploads/2017/03/promo-vidange.jpg?fit=500%2C150",
        "duree": "du 14 Mai 2020 à 14 Juin 2020",
        "prix": "prix en DHs",
        "description":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
        "dateachatpromo":"19/01/2020",
        "dureepromopub": "du 14 Juillet 2020 à 14 Aout 2020",
        "prixpromopub":"prix",
        "descriptionpromopub":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
    },
    {
        "key": "HGHJagdu6788géj8",
        "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS4zx9bLtK-_q_kuTe_gJhm8gWVT_AGms2p-Q&usqp=CAU",
        "marque": "Mercedes classe C",
        "numéro_immatriculation": "13-B-239884",
        "idvehicule": 225,
        "idpropriétaire": 3 ,
        "dateintervention": "22/08/2019",
        "dernierevidange": "19/01/2020",
        "kilometrage": "110000",
        "detail1": "detail1",
        "detailderniereintervention": "detailderniereintervention",
        "imagepromoUrl": "https://i2.wp.com/www.carideal.com/blog/wp-content/uploads/2017/03/promo-vidange.jpg?fit=500%2C150",
        "duree": "du 26 Mai 2020 à 14 Juin 2020",
        "prix": "prix en DHs",
        "description":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
        "dateachatpromo":"19/01/2020","dureepromopub": "du 14 Juillet 2020 à 14 Aout 2020",
        "prixpromopub":"prix",
        "descriptionpromopub":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",

    },
    {
        "key": "KKDAZ667fhh999",
        "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS4zx9bLtK-_q_kuTe_gJhm8gWVT_AGms2p-Q&usqp=CAU",
        "marque": "Dacia",
        "numéro_immatriculation": "15-C-2377884",
        "idvehicule": 226,
        "idpropriétaire": 3 ,
        "dateintervention": "12/01/2019",
        "dernierevidange": "19/01/2020",
        "kilometrage": "110000",
        "detail1": "detail1",
        "detailderniereintervention": "detailderniereintervention",
       "imagepromoUrl": "https://i2.wp.com/www.carideal.com/blog/wp-content/uploads/2017/03/promo-vidange.jpg?fit=500%2C150",
        "duree": "du 2 Mai 2020 à 20 Mai 2020",
        "prix": "prix en DHs",
        "description":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
        "dateachatpromo":"19/01/2020","dureepromopub": "du 14 Juillet 2020 à 14 Aout 2020",
        "prixpromopub":"prix",
        "descriptionpromopub":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",

    },
    // {
    //     "key": "hgapkksn78200bb$$$@",
    //     "imageUrl": "https://www.citroen.ma/wp-content/uploads/2016/11/NouvelleC3-blanc-banquise-AR.jpg",
    //     "marque": "Toyota",
    //     "numéro_immatriculation": "13-B-239884",
    //     "idvehicule": 225,
    //     "idpropriétaire": 5 ,
    //     "dateintervention": "28/12/2018",
    //     "dernierevidange": "19/01/2020",
    //     "kilometrage": 110000
    // },
    // {
    //     key: "16hhzdejRYVVJ@",
    //     "imageUrl": "https://www.citroen.ma/wp-content/uploads/2016/11/NouvelleC3-blanc-banquise-AR.jpg",
    //     "marque": "Dacia",
    //     "numéro_immatriculation": "13-B-239884",
    //     "idvehicule": 229,
    //     "idpropriétaire":4 ,
    //     "dateintervention": "30/05/2017",
    //     "dernierevidange": "19/01/2020",
    //     "kilometrage": 110000

    // },
    {    
        "key": "PPXDAKLE338491!!$$",
        "imageUrl": "https://i.le360.ma/fr/sites/default/files/styles/asset_image_in_body/public/assets/images/2019/01/new-renault-clio-2019-1079285.jpg",
        "marque": "Dacia",
        "numéro_immatriculation": "13-B-239884",
        "idvehicule": 229,
        "idpropriétaire":7 ,
        "dateintervention": "10/02/2017",
        "dernierevidange": "19/01/2020",
        "kilometrage": "110000",
        "detail1": "detail1",
        "detailderniereintervention": "detailderniereintervention",
        "imagepromoUrl": "https://i2.wp.com/www.carideal.com/blog/wp-content/uploads/2017/03/promo-vidange.jpg?fit=500%2C150",
        "duree": "du  Avril 2020 à Avril 2020",
        "prix": "prix en DHs",
        "description":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
        "dateachatpromo":"19/01/2020",
        "dureepromopub": "du 14 Juillet 2020 à 14 Aout 2020",
        "prixpromopub":"prix",
        "descriptionpromopub":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
    },
    {
        "key": "vqvk155712GhdzjKH",
        "imageUrl": "https://i.le360.ma/fr/sites/default/files/styles/asset_image_in_body/public/assets/images/2019/01/new-renault-clio-2019-1079285.jpg",
        "marque": "Renault ",
        "numéro_immatriculation": "15-A-11324",
        "idvehicule": 229,
        "idpropriétaire":2,
        "dateintervention": "19/01/2020",
        "dernierevidange": "19/01/2020",
        "kilometrage": "110000",
        "detail1": "detail1",
        "detailderniereintervention": "detailderniereintervention",
        "imagepromoUrl": "https://i2.wp.com/www.carideal.com/blog/wp-content/uploads/2017/03/promo-vidange.jpg?fit=500%2C150",
        "duree": "du 2 Mai 2020 à 20 Mai 2020",
        "prix": "prix en DHs",
        "description":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
        "dateachatpromo":"19/01/2020",
        "dureepromopub": "du 14 Juillet 2020 à 14 Aout 2020",
        "prixpromopub":"prix",
        "descriptionpromopub":"descdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdescdesc",
    },
]